{
 "title": "Profit",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "diff",
    "label": "起点差值",
    "query": "WITH converted AS (\n  SELECT init, total, date || 'T00:00:00Z' AS time FROM profit_stats\n)\nSELECT (total-init) FROM converted WHERE strftime('%s', time)*1000 < $__from ORDER BY time DESC LIMIT 1"
   },
   { "name": "code", "label": "个股收益", "query": "select code || name from stock" }
  ]
 },
 "panels": [
  {
   "title": "收益",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "WITH converted AS (\n  SELECT init, total, date || 'T00:00:00Z' AS time FROM profit_stats\n)\nSELECT time,\n  (total - init - $diff)/10000.0 AS 收益,\n  100.0 * (total - init - $diff)/(init + $diff) AS 收益率\nFROM converted ORDER BY time ASC",
     "rawQueryText": "WITH converted AS (\n  SELECT init, total, date || 'T00:00:00Z' AS time FROM profit_stats\n)\nSELECT time,\n  (total - init - $diff)/10000.0 AS 收益,\n  100.0 * (total - init - $diff)/(init + $diff) AS 收益率\nFROM converted ORDER BY time ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$code 收益",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "WITH converted AS (\n  SELECT amount, cost, value, date || 'T00:00:00Z' AS time FROM hold_stats where code = substr('$code', 1, 6)\n)\nSELECT time,\n  --cost/10000.0 AS 本金,\n  value/10000.0 AS 市值,\n  (value-cost)/10000.0 AS 收益,\n  amount AS 数量\nFROM converted ORDER BY time ASC",
     "rawQueryText": "WITH converted AS (\n  SELECT amount, cost, value, date || 'T00:00:00Z' AS time FROM hold_stats where code = substr('$code', 1, 6)\n)\nSELECT time,\n  --cost/10000.0 AS 本金,\n  value/10000.0 AS 市值,\n  (value-cost)/10000.0 AS 收益,\n  amount AS 数量\nFROM converted ORDER BY time ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本金-市值",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "WITH converted AS (\n  SELECT init, total, date || 'T00:00:00Z' AS time FROM profit_stats\n)\nSELECT time,\n  init/10000.0 AS 本金,\n  total/10000.0 AS 市值\nFROM converted ORDER BY time ASC",
     "rawQueryText": "WITH converted AS (\n  SELECT init, total, date || 'T00:00:00Z' AS time FROM profit_stats\n)\nSELECT time,\n  init/10000.0 AS 本金,\n  total/10000.0 AS 市值\nFROM converted ORDER BY time ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "持仓配置",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "queryText": "WITH converted AS (\n  SELECT a, b, cb, etf, etf_hk, cash, date || 'T00:00:00Z' AS time FROM profit_stats\n)\nSELECT time,\n  a/10000.0 AS A股,\n  b/10000.0 AS B股,\n  cb/10000.0 AS 转债,\n  etf/10000.0 AS ETF,\n  etf_hk/10000.0 AS HK,\n  cash/10000.0 AS 现金\nFROM converted ORDER BY time ASC",
     "rawQueryText": "WITH converted AS (\n  SELECT a, b, cb, etf, etf_hk, cash, date || 'T00:00:00Z' AS time FROM profit_stats\n)\nSELECT time,\n  a/10000.0 AS A股,\n  b/10000.0 AS B股,\n  cb/10000.0 AS 转债,\n  etf/10000.0 AS ETF,\n  etf_hk/10000.0 AS HK,\n  cash/10000.0 AS 现金\nFROM converted ORDER BY time ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "账户1",
   "type": "table",
   "gridPos": { "h": 24, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 1\norder by stock.code",
     "rawQueryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 1\norder by stock.code",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "账户2",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 2\norder by stock.code",
     "rawQueryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 2\norder by stock.code",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "账户3",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 3\norder by stock.code",
     "rawQueryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 3\norder by stock.code",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "账户4",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 4\norder by stock.code",
     "rawQueryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 4\norder by stock.code",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "账户5",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 5\norder by stock.code",
     "rawQueryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 5\norder by stock.code",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "账户6",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 6\norder by stock.code",
     "rawQueryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 6\norder by stock.code",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "交易记录",
   "type": "table",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%d', date) AS 日期,\n  stock.code AS 代码,\n  stock.name AS 名称,\n  price AS 成交价,\n  amount AS 数量,\n  note AS 备注\nFROM trade_history, stock\nwhere trade_history.code = stock.code and strftime('%s', date)*1000 >= $__from and strftime('%s', date)*1000 <= $__to and trade_history.code NOT IN('511360')\norder by date desc, id desc",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%d', date) AS 日期,\n  stock.code AS 代码,\n  stock.name AS 名称,\n  price AS 成交价,\n  amount AS 数量,\n  note AS 备注\nFROM trade_history, stock\nwhere trade_history.code = stock.code and strftime('%s', date)*1000 >= $__from and strftime('%s', date)*1000 <= $__to and trade_history.code NOT IN('511360')\norder by date desc, id desc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "账户7",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
   "targets": [
    {
     "queryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 7\norder by stock.code",
     "rawQueryText": "SELECT\n  stock.name AS 名称,\n  amount AS 数量,\n  ROUND(1.0*cost/amount, 3) AS 成本价\nFROM holdings, stock\nwhere holdings.code = stock.code and holdings.account_id = 7\norder by stock.code",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}